language: python

python:
  - 2.7
  - 3.6

addons:
  apt:
    packages:
    - gfortran

script:
  - bash build_all.sh
  - mv bin bin_linux
  - ./bin/focus
  - ./bin/sginfo
  - ./bin/bin/dls76.x
  - ./bin/bin/kriber.x
  - python setup.py install
