language: python
python:
- 2.7
  # - 3.6
addons:
  apt:
    packages:
    - gfortran
    - subversion

before_install:
- pwd
- ls -la

script:
- bash build_all.sh
- cp -r bin bin_linux
- python setup.py install
- bash build_sayperm.sh

notifications:
  email: false
  slack:
    secure: $SLACKURL
