language: python
python:
- 2.7
  # - 3.6
addons:
  apt:
    packages:
    - gfortran
    - subversion

before_install:
- pwd
- ls -la

script:
- bash build_all.sh
- mv bin bin_linux
  # - chmod 700 ./bin/focus
  # - "./bin/focus"
  # - "./bin/sginfo"
  # - "./bin/bin/dls76.x"
  # - "./bin/bin/kriber.x"
- python setup.py install
- bash build_sayperm.sh

notifications:
  email: false
  slack:
    secure: $SLACKURL
