language: python
python:
- 2.7
  # - 3.6
addons:
  apt:
    packages:
    - gfortran
    - subversion

before_install:
- pwd
- ls -la

script:
- bash build_all.sh
- mv bin bin_linux
  # - chmod 700 ./bin/focus
  # - "./bin/focus"
  # - "./bin/sginfo"
  # - "./bin/bin/dls76.x"
  # - "./bin/bin/kriber.x"
- python setup.py install
- cd focus_package/focus/src/sayperm;make

notifications:
  email: false
  slack:
    secure: lfWN+JaZrpyd1anxVCufjZIP3c8IMHYoSIeI8duymT4nXrvQF7mN3Qi8EKScXDzuhWYnfMZHq0nxvt7AWeJCB7FAymdkkNOMOQ/Cpk+gVWJsx7dR0RrS9rbHanb6s9rcibwIGtAPGGb8VRb4FKau55TYf0dgCGW0W/6sDQpYblkzitt3QSWnspC5Mx/Vc+fntGtDgPvL7Vs2AUoa0eIWhuCDc27rFGf/YbtRlHsQZq8e+BwAVe8iP/PYzYHPxdsLThBU2oz03GUFkTS7QmHZTer4CbOpOHvY//piLZP2N2oc92JXjEj9mOBMAUXlN0wtvx8fmgSi9a4tm7KjgZczBo7TOwtiioUz95Mt1gQHudz0Li1jJ0G65KSvyjbxm5HP+WBa4IrH17W/XBCpaYelH5Q5nQ02VVwFrKPvKvPfsR+eEZg6pMH8BrWvpD/c/oXE79QOm5R9YGT84Ps+jV84oy8AWw6wXztZelCliCp2CVVuC2X7zHtqDwKff/knaj7/t1MSPUNUFd83ojcBmCoopesdd7bwQYvibavuYQhjNSZm+XDyWQ+MtuAilBoyNYpjSLMo93OfB2LcnJfDy9Gx0UwFRlulqzW8jrLDioIHGdviWzmkFzQeMc74NEvgecClCHvzm4bg3vkDa74mGU9ZCAX769PNxJ5NK9Qpp71ZAE8=
